<a href="https://colab.research.google.com/github/emamanni/AnalisiDeiDati_25-26/blob/main/04_LaLibreriaNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science hands-on review: la libreria NumPy

NumPy (abbreviazione di *Numerical Python*) fornisce un'interfaccia efficiente per memorizzare e operare su buffer di dati densi.

In un certo senso, gli array NumPy sono come il tipo `list` incorporato in Python, ma gli array NumPy forniscono una memorizzazione e operazioni sui dati molto più efficienti man mano che le dimensioni degli array aumentano.

Gli array NumPy costituiscono il nucleo di quasi tutto l'ecosistema di strumenti per la data science in Python.

Una volta installato, si può importare NumPy e controllare la versione ...

In [1]:
import numpy
numpy.__version__

'2.0.2'

Per convenzione, tipicamente si importa NumPy usando `np` come alias ...

In [3]:
import numpy as np

##Creazione di array a partire da liste

Per creare un array a partire da una lista:

In [ ]:
# array di interi
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Si tenga presente che, a differenza delle liste Python, gli array NumPy possono contenere solo dati dello stesso tipo. Se i tipi non corrispondono, NumPy esegue l'upcast in base alle sue regole di "type promotion". Nel caso seguente, i numeri interi sono stati trasformati in virgola mobile:

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Per impostare esplicitamente il tipo di dati dell'array risultante, si può usare la parola chiave `dtype`:

In [ ]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

Infine, a differenza delle liste di Python, che sono sempre sequenze monodimensionali, gli array di NumPy possono essere multidimensionali. Di seguito un modo per inizializzare un array multidimensionale utilizzando un elenco di liste. Le liste interne sono trattate come righe dell'array bidimensionale risultante.

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 10]])

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [10, 11, 12]])

##Creazione di array da zero

Soprattutto per gli array più grandi, è più efficiente creare gli array da zero utilizzando le routine integrate in NumPy.

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,3))

array([[0.56279966, 0.16146665, 0.36357068],
       [0.42821137, 0.23652355, 0.25115529],
       [0.03706046, 0.51081361, 0.5617694 ]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

##Manipolazione degli array NumPy

La manipolazione dei dati in Python è quasi sinonimo di manipolazione di array NumPy. Nelle sezioni successive si fornirannole basi per la manipolazione degli array NumPy per accedere ai dati e ai subarray, nonché per dividere, rimodellare e unire gli array.

###Attributi degli array NumPy

Ogni array ha degli attributi, tra cui `ndim` (il numero di dimensioni), `shape` (la dimensione di ogni dimensione), `size` (la dimensione totale dell'array) e `dtype` (il tipo di ogni elemento).

In [5]:
x = np.random.random((3,3))

print(x)
print("x ndim =", x.ndim)
print("x shape =", x.shape)
print("x size =", x.size)
print("x dtype =", x.dtype)

[[0.87143398 0.27248179 0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]
x ndim = 2
x shape = (3, 3)
x size = 9
x dtype = float64


###Indicizzazione di un array: accedere ad un elemento singolo

In un array monodimensionale, si può accedere al valore i-esimo (contando da zero) specificando l'indice desiderato tra parentesi quadre, proprio come avviene con le liste Python.

In [6]:
x1 = np.arange(0, 20, 2)
print(x1)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
print(x1[0])

0


In [10]:
print(x1[9])

18


Per considerare gli indici a partire dalla fine di un array, occorre considerare valori negativi.

In [11]:
print(x1[-1])

18


In [12]:
print(x1[-4])

12


In un array multidimensionale, si può accedere ad un elemento utilizzando una tupla (riga, colonna).

In [15]:
print(x)

[[0.87143398 0.27248179 0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


In [14]:
print(x[0,0])

0.8714339800944961


In [16]:
print(x[2,0])

0.21980322982500633


In [17]:
print(x[2, -1])

0.6388815923150912


È possibile modificare dei valori utilizzando gli indici.

In [18]:
x[0,0] = 0.45
print(x)

[[0.45       0.27248179 0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


Si ricordi che il tipo dei dati contenuti in un array è fisso. Pertanto, se nell'array `x` precedente si proverà ad inserire un valore intero, esso sarà convertito nel corrispondente valore in virgola mobile.

In [24]:
x[0,1] = 7
print(x)

[[0.45       7.         0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


###Slicing di un array: accedere a sotto-array

Così come si possono usare le parentesi quadre per accedere ai singoli elementi di un array, si possono anche usarle per accedere a sotto-array con la notazione slice, contrassegnata dai due punti (:). La sintassi di NumPy per accedere a uno slice di un array `x`, è:

`x[start:stop:step]`

Se uno qualsiasi di questi valori non è specificato, i valori di default sono `start=0`, `stop=<numero di dimensioni>`, `step=1`.

####Sotto-array ad una dimensione

In [25]:
print(x1)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
print(x1[:3:])

[0 2 4]


In [28]:
print(x1[1:4:1])

[2 4 6]


In [29]:
print(x1[::2])

[ 0  4  8 12 16]


In [30]:
print(x1[1::2])

[ 2  6 10 14 18]


Quando il valore di `step` è negativo, i valori predefiniti di `start` e `stop` vengono scambiati. Questo diventa un modo conveniente per invertire un array.

In [31]:
print(x1[::-1])

[18 16 14 12 10  8  6  4  2  0]


In [32]:
print(x1[4::-2])

[8 4 0]


####Sottoarray-multidimensionali
Il funzionamento è analogo, con slice multipli separati da virgole.

In [33]:
print(x)

[[0.45       7.         0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


In [34]:
print(x[:2, :2])

[[0.45       7.        ]
 [0.18867434 0.67540837]]


In [35]:
print(x[:3, ::2])

[[0.45       0.85206306]
 [0.18867434 0.18175592]
 [0.21980323 0.63888159]]


In [37]:
print(x)
print(x[::-1, ::-1])

[[0.45       7.         0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]
[[0.63888159 0.71810271 0.21980323]
 [0.18175592 0.67540837 0.18867434]
 [0.85206306 7.         0.45      ]]


####Accedere a righe e colonne di un array multidimensionale
Una pratica frequentemente utilizzata è l'accesso a singole righe o colonne di un array. Questo può essere fatto combinando l'indicizzazione e lo slicing, utilizzando uno slice vuoto contrassegnato da un singolo `:`

In [38]:
print(x)

[[0.45       7.         0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


In [39]:
print(x[:, 0])

[0.45       0.18867434 0.21980323]


In [40]:
print(x[0, :])

[0.45       7.         0.85206306]


Nel caso di accesso ad una riga, lo slice vuoto può essere omesso per ottenere una sintassi più compatta.

In [41]:
print(x[0])

[0.45       7.         0.85206306]


###Sotto-array come viste
A differenza degli slice di liste Python, gli slice di array NumPy sono restituiti come viste piuttosto che come copie dei dati dell'array. Consideriamo il l'array bidimensionale precedente.

In [42]:
print(x)

[[0.45       7.         0.85206306]
 [0.18867434 0.67540837 0.18175592]
 [0.21980323 0.71810271 0.63888159]]


Estraiamo un sotto-array 2x2.

In [43]:
x_estratto = x[:2, :2]
print(x_estratto)

[[0.45       7.        ]
 [0.18867434 0.67540837]]


Ora, se modifichiamo questo sotto-array, vedremo che l'array originale è cambiato!

In [45]:
x_estratto[0,0] = 10
print(x_estratto)

[[10.          7.        ]
 [ 0.18867434  0.67540837]]


In [46]:
print(x)

[[10.          7.          0.85206306]
 [ 0.18867434  0.67540837  0.18175592]
 [ 0.21980323  0.71810271  0.63888159]]


###Creare copie di un array
A volte è utile copiare esplicitamente i dati all'interno di un array o di un sotto-array. Questo può essere fatto con il metodo `copy`.

In [47]:
x_estratto_copia = x[:2, :2].copy()
print(x_estratto_copia)

[[10.          7.        ]
 [ 0.18867434  0.67540837]]


Se ora modifichiamo questo sotto-array, l'array originale rimane invariato.

In [48]:
x_estratto_copia[0,0] = 18.4
print(x_estratto_copia)

[[18.4         7.        ]
 [ 0.18867434  0.67540837]]


In [49]:
print(x)

[[10.          7.          0.85206306]
 [ 0.18867434  0.67540837  0.18175592]
 [ 0.21980323  0.71810271  0.63888159]]


###Concatenazione e separazione di array
NumPy fornisce anche strumenti per combinare più array in uno solo e per dividere un singolo array in più array.
####Concatenazione di array
La concatenazione, o l'unione di due array in NumPy, si realizza principalmente con le routine `np.concatenate`, `np.vstack` e `np.hstack`. `np.concatenate` prende come primo parametro una tupla o un elenco di array.

In [50]:
a = np.array([1, 2, 3])
b = np.array([30, 30, 30])
print(np.concatenate([a,b]))

[ 1  2  3 30 30 30]


Si possono concatenare anche più di due array.

In [52]:
c = np.array([5, 6, 7])
print(np.concatenate([a, c, b]))

[ 1  2  3  5  6  7 30 30 30]


Concatenare array bidimensionali.

In [54]:
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([[7,8,9], [10,11,12]])
print(np.concatenate([array1, array2]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
print(np.concatenate([array1, array2], axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Per array di dimensioni miste, è conveniente usare le funzioni `np.vstack` (stack verticale) e `np.hstack` (stack orizzontale)

In [56]:
print(np.vstack([x, array1]))

[[10.          7.          0.85206306]
 [ 0.18867434  0.67540837  0.18175592]
 [ 0.21980323  0.71810271  0.63888159]
 [ 1.          2.          3.        ]
 [ 4.          5.          6.        ]]


In [57]:
y = np.array([[99],
              [99]])
print(np.hstack([array1, y]))

[[ 1  2  3 99]
 [ 4  5  6 99]]


####Separazione di array
L'opposto della concatenazione è la separazione, implementata dalle funzioni `np.split`, `np.hsplit` e `np.vsplit`. Per ciascuna di esse è possibile passare un elenco di indici che indicano i punti di divisione.

In [58]:
array3 = np.array([1,2,3,99,99,3,2,1])
x1, x2, x3 = np.split(array3, [3,5])
print(x1, x2, x3)
x4, x5 = np.split(array3, [3])
print(x4, x5)

[1 2 3] [99 99] [3 2 1]
[1 2 3] [99 99  3  2  1]


In [59]:
h = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [62]:
upper, lower = np.vsplit(h, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [63]:
left, right = np.hsplit(h, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##Eseguire calcoli su array NumPy: le Universal Functions (`ufuncs`)
Eseguire calcoli sugli array di NumPy può essere molto veloce o molto lento. La chiave per rendere queste operazioni veloci è l'uso di operazioni vettoriali, generalmente implementate attraverso le funzioni universali di NumPy (ufuncs).

###Introduzione alle Ufuncs
Per molti tipi di operazioni, NumPy fornisce una comoda interfaccia, nota come operazione vettoriale. Per operazioni semplici come la divisione elementare, la vettorizzazione è semplice come usare gli operatori aritmetici Python direttamente sull'oggetto array. L'approccio vettoriale è stato progettato per spingere il ciclo nel livello compilato che sta alla base di NumPy, rendendo l'esecuzione molto più veloce.

Le operazioni vettoriali in NumPy sono implementate tramite ufuncs, il cui scopo principale è quello di eseguire rapidamente operazioni ripetute sui valori degli array NumPy.

Ad esempio, su un array monodimensionale:

In [64]:
valori = np.array([9, 4, 1, 3, 8])
print(valori)

[9 4 1 3 8]


In [65]:
print(1.0 / valori)

[0.11111111 0.25       1.         0.33333333 0.125     ]


Si può anche operare tra 2 array:

In [66]:
vettore1 = np.arange(5)
vettore2 = np.arange(1, 6)
print(vettore1)
print(vettore2)
print(vettore1 / vettore2)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


Le operazioni ufunc non sono limitate agli array monodimensionali. Possono agire anche su array multidimensionali:

In [67]:
x = np.array([[1,2], [3,4]])
print(2 ** x)

[[ 2  4]
 [ 8 16]]


###Le diverse tipologie di Ufuncs
Le Ufuncs esistono in due varianti: ufuncs unarie, che operano su un singolo input, e ufuncs binarie, che operano su due input.

####Operazioni aritmetiche sugli array
È possibile utilizzare le normali operazioni di addizione, sottrazione, moltiplicazione e divisione:

In [68]:
x = np.arange(0,4)
print("x = ", x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x * 2 =", x*2)
print("x / 2 =", x/2)

x =  [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]


Esiste anche una ufunc unaria per la negazione, un operatore `**` per l'elevamento a potenza e un operatore `%` per il modulo:

In [70]:
print(x)
print("-x =", -x)
print("x ** 3 =", x**3)
print("x % 2 =", x%2)

[0 1 2 3]
-x = [ 0 -1 -2 -3]
x ** 3 = [ 0  1  8 27]
x % 2 = [0 1 0 1]


Inoltre, queste possono essere collegate tra loro nel modo desiderato, rispettando l'ordine standard delle operazioni:

In [71]:
print(-(0.5*x + 1) ** 2)

[-1.   -2.25 -4.   -6.25]


Tutte queste operazioni aritmetiche sono semplicemente dei comodi wrapper attorno a specifiche ufunc integrate in NumPy. Ad esempio, l'operatore + è un wrapper per l'ufunc `add`:

In [72]:
print(np.add(x,2))

[2 3 4 5]


La seguente tabella elenca gli operatori aritmetici implementati in NumPy:

| Operatore    | Ufunc corrispondente  | Descrizione                         |
|-------------|-------------------|-------------------------------------|
|`+`          |`np.add`           |Addizione (es., `1 + 1 = 2`)         |
|`-`          |`np.subtract`      |Sottrazione (es., `3 - 2 = 1`)      |
|`-`          |`np.negative`      |Negazione unaria (es., `-2`)          |
|`*`          |`np.multiply`      |Moltiplicazione (es., `2 * 3 = 6`)   |
|`/`          |`np.divide`        |Divisione (es., `3 / 2 = 1.5`)       |
|`//`         |`np.floor_divide`  |Divisione con arrotondamento (es., `3 // 2 = 1`)  |
|`**`         |`np.power`         |Elevamento a potenza (es., `2 ** 3 = 8`)  |
|`%`          |`np.mod`           |Modulo/resto (es., `9 % 4 = 1`)|

####Valore assoluto
Con NumPy è possibile anche utilizzare la funzione valore assoluto integrata in Python:

In [73]:
x = np.array([-2, -1, 0, 1, 2])
print(x)
print(abs(x))

[-2 -1  0  1  2]
[2 1 0 1 2]


La corrispondentu ufunc di NumPy è `np.absolute` (è possibile anche utilizzare l'alias `np.abs`):

In [74]:
print(np.absolute(x))

[2 1 0 1 2]


In [75]:
print(np.abs(x))

[2 1 0 1 2]


####Funzioni trigonometriche
Altre ufunc molto utili sono quelle relative a funzioni trigonometriche.

Definiamo innanzitutto un array di angoli:

In [76]:
theta = np.linspace(0, np.pi, 3)
print(theta)

[0.         1.57079633 3.14159265]


Applichiamo alcune funzioni trigonometriche:

In [77]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


I valori sono calcolati con la precisione della macchina, per cui i valori che dovrebbero essere zero non sempre corrispondono esattamente a zero. Sono disponibili anche funzioni trigonometriche inverse:

In [78]:
x = np.array([-1, 0, 1])
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1  0  1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


####Esponenziali e logaritmi
Tra le ufunc NumPy sono presenti anche quelle relative ad esponenziali e logaritmi (sia logaritmo naturale, che in base 2, che in base 10):

In [80]:
x = [1, 2, 3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3.0, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3.  9. 27.]


In [81]:
x = np.array([1, 2, 4, 10])
print("x = ", x)
print("ln(x) =", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [ 1  2  4 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


##Funzioni di aggregazione
Un primo passo nell'esplorazione di qualsiasi dataset è spesso il calcolo di statistiche di sintesi. Forse le statistiche di riepilogo più comuni sono la media e la deviazione standard, che consentono di riassumere i valori “tipici” di un dataset, ma sono utili anche altre aggregazioni (la somma, il prodotto, la mediana, il minimo e il massimo, i quantili, ecc.)

NumPy dispone di varie funzioni di aggregazione integrate per lavorare sugli array.

###Sommare i valori di un array
Una prima funzione è per il calcolo della somma degli elementi di un array. Si può utilizzare anche la funzione integrata `sum` di Python ma, per array di grandi dimensioni, la funzione `sum` di NumPy è molto più efficiente (come si evince dall'esempio seguente in cui è utilizzata `timeit`, una libreria integrata di Python per misurare il tempo di esecuzione di snippet di codice).

In [84]:
import timeit

rng = np.random.default_rng()
big_array = rng.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

106 ms ± 7.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
461 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


###Minimo e massimo
Per calcolare il minimo e massimo valore tra gli elementi di un array è possibile utilizzare:

In [86]:
print(np.min(big_array))
print(np.max(big_array))

4.3600319918901675e-06
0.9999995144203121


Alternativamente, una sintassi più concisa prevede di utilizzare i metodi dell'array stesso (ciò vale anche per la somma):

In [87]:
print(big_array.min(), big_array.max(), big_array.sum())

4.3600319918901675e-06 0.9999995144203121 500225.16118848074


###Altre funzioni di aggregazione
La seguente tabella fornisce un elenco di utili funzioni di aggregazione disponibili in NumPy.

|Nome    |   Versione NaN-safe| Descrizione                                   |
|-----------------|-------------------|-----------------------------------------------|
| `np.sum`        | `np.nansum`       | Somma degli elementi                       |
| `np.prod`       | `np.nanprod`      | Prodotto degli elementi                    |
| `np.mean`       | `np.nanmean`      | Media degli elementi                       |
| `np.std`        | `np.nanstd`       | Deviazione standard                    |
| `np.var`        | `np.nanvar`       | Varianza                              |
| `np.min`        | `np.nanmin`       | Trova il minimo valore                            |
| `np.max`        | `np.nanmax`       | Trova il massimo valore                            |
| `np.argmin`     | `np.nanargmin`    | Trova l'indice del minimo valore                   |
| `np.argmax`     | `np.nanargmax`    | Trova l'indice del massimo valore                   |
| `np.median`     | `np.nanmedian`    | Calcola la mediana degli elementi                    |
| `np.percentile` | `np.nanpercentile`| Calcola i percentili     |
| `np.any`        | N/A               | Valuta se un qualsiasi elemento è vero        |
| `np.all`        | N/A               | Valuta se tutti gli elementi sono veri        |


###Operatori di confronto
NumPy implementa anche operatori di confronto come < (minore di) e > (maggiore di) come ufunc che operano elemento per elemento. Il risultato di questi operatori di confronto è sempre un array di tipo booleano. Sono disponibili tutte e sei le operazioni di confronto standard.

In [88]:
x = np.array([1, 2, 3, 4, 5])
print(x < 3)

[ True  True False False False]


In [89]:
print(x > 3)

[False False False  True  True]


In [90]:
print(x <= 3)

[ True  True  True False False]


In [91]:
print(x >= 3)

[False False  True  True  True]


In [92]:
print(x != 3)

[ True  True False  True  True]


In [93]:
print(x == 3)

[False False  True False False]


È anche possibile eseguire un confronto elemento per elemento tra due array e includere espressioni composte:

In [95]:
array1 = 2*x
print(array1)
array2 = x**2
print(array2)
array3 = (array1 == array2)
print(array3)

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[False  True False False False]


Come nel caso degli operatori aritmetici, anche gli operatori di confronto sono implementati come ufunc in NumPy; ad esempio, quando si scrive `x < 3`, internamente NumPy utilizza `np.less(x, 3)`. Qui è riportato un riepilogo degli operatori di confronto e dello loro ufunc equivalenti:

| Operatore    | ufunc equivalente | Operatore   | ufunc equivalente|
|-------------|-------------------|------------|------------------|
|`==`         |`np.equal`         |`!=`        |`np.not_equal`    |
|`<`          |`np.less`          |`<=`        |`np.less_equal`   |
|`>`          |`np.greater`       |`>=`        |`np.greater_equal`|

###Lavorare con array booleani
Dato un array booleano, è possibile eseguire una serie di operazioni utili. Facciamo riferimento all'array bidimensionale `x`:

In [96]:
x = np.array([[9, 4, 0, 3], [2, 5, 7, 3], [9, 9, 4, 0]])
print(x)

[[9 4 0 3]
 [2 5 7 3]
 [9 9 4 0]]


####Contare il numero di elementi
Per contare il numero di elementi `True` in un array booleano, è utile `np.count_nonzero`:

In [97]:
print(np.count_nonzero(x < 6))

8


Un modo alternativo è utilizzare `np.sum`; in questo caso `False` è interpretato come `0`, mentre `True` è interpretato come `1`:

In [98]:
print(np.sum(x < 6))

8


Il vantaggio di `np.sum` è che, come per altre funzioni di aggregazione di NumPy, questa somma può essere fatta anche lungo le righe o le colonne. Ad esempio, lo snippet seguente conta il numero di elementi minori di 6 su ciascuna riga:

In [99]:
print(np.sum(x < 6, axis=1))

[3 3 2]


####Operatori booleani
Supponiamo di voler contare il numero di elementi che verifica contemporaneamente due condizioni. Questo tipo di operazione può essere ottenuta con gli operatori logici di Python che operano bit a bit, ovvero `&`, `|`, `^` e `~` (and, or, or esclusivo e not, rispettivamente), o con le corrispondenti ufunc di NumPy. Ad esempio, per contare quanti elementi sono contemporaneamente minori di 6 e pari:

In [100]:
print(np.sum( (x<6) & (x%2 == 0) ))

5


La tabella seguente riassume gli operatori logici booleani e le corrispondenti ufunc:

| Operatore    | ufunc equivalente  | Operatore    | ufunc equivalente |
|-------------|-------------------|-------------|-------------------|
|`&`          |`np.bitwise_and`   |&#124;       |`np.bitwise_or`    |
|`^`          |`np.bitwise_xor`   |`~`          |`np.bitwise_not`   |

###Array booleani come "maschere" (masks)
Prima abbiamo calcolato dei valori aggregati direttamente su array booleani interi. Un modello più potente è quello di usare gli array booleani come maschere, per selezionare particolari sottoinsiemi dei dati stessi.

Con riferimento al precedente array `x`, si è visto che è possibile ottenere facilmente un array con valori `True` o `False`, a seconda che una certa condizione sia verificata o meno. Ad esempio:

In [101]:
print(x < 6)

[[False  True  True  True]
 [ True  True False  True]
 [False False  True  True]]


Per selezionare solo i valori dell'array che soddisfano la condizione data, si può procedere effettuando un'operazione nota come *masking*:

In [102]:
print(x[x<6])

[4 0 3 2 5 3 4 0]


Ciò che viene restituito è un array monodimensionale con tutti i valori che soddisfano la condizione, ovvero solo i valori nelle posizioni in cui l'array mask contiene `True`.

##Ordinamento (sorting) di array
Python dispone di alcune funzioni e metodi integrati per ordinare liste e altri oggetti iterabili. La funzione `sorted` prende in input una lista e ne restituisce una copia ordinata. Ad esempio:

In [103]:
lista = [3, 1, 4 , 1, 5, 9, 2, 6]
print(lista)
print(sorted(lista))

[3, 1, 4, 1, 5, 9, 2, 6]
[1, 1, 2, 3, 4, 5, 6, 9]


Per contro, il metodo `sort` agisce direttamente sulla lista da ordinare:

In [105]:
print(lista)
lista.sort()
print(lista)

[3, 1, 4, 1, 5, 9, 2, 6]
[1, 1, 2, 3, 4, 5, 6, 9]


###Ordinamento con NumPy
La funzione `np.sort` è analoga a `sorted`, restituendo una copia dell'array:

In [106]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))

[1 2 3 4 5]


Per effettuare l'ordinamento direttamente sull'array:

In [108]:
print(x)
x.sort()
print(x)

[2 1 4 3 5]
[1 2 3 4 5]


Se si vogliono ottenere gli indici degli elementi ordinati, si utilizza la funzione `argsort`:

In [110]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


Il primo elemento dell'array restituito contiene l'indice dell'elemento più piccolo, il secondo elemento contiene l'indice del secondo più piccolo e così via.

####Ordinamento lungo le righe o lungo le colonne
Una caratteristica utile degli algoritmi di ordinamento di NumPy è la possibilità di ordinare lungo specifiche righe o colonne di un array multidimensionale utilizzando l'argomento `axis`.

In [111]:
x = np.array([[9, 4, 0, 3], [2, 5, 7, 3], [9, 9, 4, 0]])
print(x)

[[9 4 0 3]
 [2 5 7 3]
 [9 9 4 0]]


In [112]:
print(np.sort(x, axis=0))

[[2 4 0 0]
 [9 5 4 3]
 [9 9 7 3]]


In [113]:
print(np.sort(x, axis=1))

[[0 3 4 9]
 [2 3 5 7]
 [0 4 9 9]]
