<a href="https://colab.research.google.com/github/emamanni/AnalisiDeiDati_25-26/blob/main/10_BasicMathReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic math review: Algebra Lineare

Nel presente notebook sarà illustrato l'utilizzo di NumPy per creare, manipolare ed effettuare operazioni su scalari, vettori e matrici.

## Scalari e vettori

In precedenza, abbiamo già visto come definire scalari e vettori ed accedere ad elementi in essi contenuti.

Le principali funzionalità sono riportate di seguito.

In [ ]:
import numpy as np

In [ ]:
# Uno scalare
a = 5
print(a)
print("dtype:", type(a), "\n")
a = 5.
print(a)
print("dtype:", type(a))

5
dtype: <class 'int'> 

5.0
dtype: <class 'float'>


In [ ]:
# Rappresentazione NumPy del vettore [1, 2, 3, 4]
x = np.array([1,2,3,4])
print(x)
print("dtype:", x.dtype, "\n")

x = np.array([1.,2.,3.,4.])
print(x)
print("dtype:", x.dtype)

[1 2 3 4]
dtype: int64 

[1. 2. 3. 4.]
dtype: float64


In [ ]:
print("x[1] = ", x[1])   # accedere a singoli elementi del vettore
print("x[-1] = ", x[-1]) # per indicizzare a partire dalla fine del vettore, è possibile utilizzare indici negativi
print("Dimensioni di x", x.shape,)
x[1] = -33  # i valori possono essere modificati anche utilizzando una qualsiasi delle notazioni di cui sopra
print("x[1] dopo la modifica = ", x[1])
x[-1] = -44
print("x[-1] dopo la modifica = ", x[-1])
print("x dall'indice 2 in poi:", x[2:])  # array slicing, cioè accedere a sotto-vettori

x[1] =  2.0
x[-1] =  4.0
Dimensioni di x (4,)
x[1] dopo la modifica =  -33.0
x[-1] dopo la modifica =  -44.0
x dall'indice 2 in poi: [  3. -44.]


In [ ]:
# La funzione arange crea un vettore composto da una sequenza di numeri
b = np.arange(0, 11)
print(b, "\n")

c = np.arange(0., 2., 0.4)
print(c, "\n")

[ 0  1  2  3  4  5  6  7  8  9 10] 

[0.  0.4 0.8 1.2 1.6] 



In [ ]:
# L'aritmetica in virgola mobile può causare problemi con valori non interi
# del parametro che rappresenta il passo di incremento
# Nell'esempio seguente, ci si aspetterebbe che l'ultimo valore di questa
# matrice fosse 1.8, ma in realtà è 2.1
d = np.arange(0., 2.1, 0.3)
print(d)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1]


In [ ]:
# Un'alternativa ad arange che risolve il problema
e = np.linspace(0.,3.5,8)
print(e)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
# Le funzioni zeroes e ones

# Le tuple dell'elenco degli argomenti definiscono la forma dei vettori
f = np.zeros(4)
print(f, "\n")

g = np.ones(5)
print(g)

[0. 0. 0. 0.] 

[1. 1. 1. 1. 1.]


## Matrici

Di seguito l'utilizzo di NumPy per definire matrici, per accedere a loro elementi singoli o a sotto-matrici.

In [ ]:
A = np.array([[1,0,0], [0,1,0], [0,0,1]])
print("Matrice A:\n", A, "\n")
print("A[0][0]:", A[0][0], "\n")   # accedere a un singolo elemento della matrice
print("Dimensioni della matrice A:", A.shape, "\n")
A[0][1] = -33  # modificare un singolo elemento della matrice
print("Matrice A dopo la modifica di A[0][1]:\n", A, "\n")
print("Sotto-matrice A[1:3, :2]:\n", A[1:3, :2])  # accedere a sotto-matrici tramite slicing

Matrice A:
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 

A[0][0]: 1 

Dimensioni della matrice A: (3, 3) 

Matrice A dopo la modifica di A[0][1]:
 [[  1 -33   0]
 [  0   1   0]
 [  0   0   1]] 

Sotto-matrice A[1:3, :2]:
 [[0 1]
 [0 0]]


In [ ]:
# Creazione di una matrice tramite reshaping di un vettore
x = np.array([1,2,3,4,5,6,7,8,9])
C = x.reshape(3,3)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
print(x)
print("Dimensioni di x:", x.shape, "\n")
x = x.reshape(3,1)  # vettore colonna attraverso reshape
print(x)
print("Dimensioni di x:", x.shape, "\n")
x = x.reshape(1,3)  # vettore riga attraverso reshape
print(x)
print("Dimensioni di x:", x.shape)

[1 2 3]
Dimensioni di x: (3,) 

[[1]
 [2]
 [3]]
Dimensioni di x: (3, 1) 

[[1 2 3]]
Dimensioni di x: (1, 3)


In [ ]:
# Matrice identità di dimensione n (es: n = 3)
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Tensori

In [ ]:
T1 = np.array([[[1,0,0], [0,1,0]], [[0,0,1], [1,0,0]]])
print("Tensore T1:\n", T1, "\n")
print("Dimensione di T1:", T1.shape, "\n")


T2 = np.arange(27)
T2 = T2.reshape(3,3,3)
print("Tensore T2:\n", T2, "\n")
print("Dimensione di T2:", T2.shape, "\n")

Tensore T1:
 [[[1 0 0]
  [0 1 0]]

 [[0 0 1]
  [1 0 0]]] 

Dimensione di T1: (2, 2, 3) 

Tensore T2:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

Dimensione di T2: (3, 3, 3) 



## Operazioni con le matrici

In [ ]:
# trasposta di una matrice
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A.transpose()
print(A, "\n")
A = A.transpose()
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# somma di matrici (di ugual dimensione)
D = A + I
print(D)

[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]


In [ ]:
# moltiplicazione di una matrice per uno scalare
a = 3
E = a * D
print(E)

[[ 6. 12. 21.]
 [ 6. 18. 24.]
 [ 9. 18. 30.]]


In [ ]:
# prodotto matriciale C = AB
# A (4x2)
# B (2x3)
A = np.array([[1,2], [4,5], [7,8], [3,6]])
B = np.array([[1,2,3], [4,5,6]])
print("Matrice A di dimensione", A.shape,":\n", A)
print("Matrice B di dimensione", B.shape,":\n", B)
C = np.matmul(A, B)
print("Matrice C = AB di dimensione", C.shape,":\n", C)

Matrice A di dimensione (4, 2) :
 [[1 2]
 [4 5]
 [7 8]
 [3 6]]
Matrice B di dimensione (2, 3) :
 [[1 2 3]
 [4 5 6]]
Matrice C = AB di dimensione (4, 3) :
 [[ 9 12 15]
 [24 33 42]
 [39 54 69]
 [27 36 45]]


In [ ]:
# prodotto tra vettori a^T b vs a b^T
x = np.array([1, 2, 3])
a = x.reshape(1,3)  # vettore riga attraverso reshape
print("Vettore a^T:\n", a)
print("Dimensioni di a^T:", a.shape, "\n")

b = x.reshape(3,1)  # vettore colonna attraverso reshape
print("Vettore b:\n", b)
print("Dimensioni di b:", b.shape, "\n")

c = np.dot(a, b)
print("c = a^T b:\n",c)
print("Dimensioni di c:", c.shape, "\n")

a = x.reshape(3,1)  # vettore colonna attraverso reshape
print("Vettore a:\n", a)
print("Dimensioni di a:", a.shape, "\n")

b = x.reshape(1,3)  # vettore riga attraverso reshape
print("Vettore b^T:\n", b)
print("Dimensioni di b^T:", b.shape, "\n")

c = np.dot(a, b)
print("c = a b^T:\n",c)
print("Dimensioni di c:", c.shape, "\n")

Vettore a^T:
 [[1 2 3]]
Dimensioni di a^T: (1, 3) 

Vettore b:
 [[1]
 [2]
 [3]]
Dimensioni di b: (3, 1) 

c = a^T b:
 [[14]]
Dimensioni di c: (1, 1) 

Vettore a:
 [[1]
 [2]
 [3]]
Dimensioni di a: (3, 1) 

Vettore b^T:
 [[1 2 3]]
Dimensioni di b^T: (1, 3) 

c = a b^T:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Dimensioni di c: (3, 3) 



In [ ]:
# Proprietà del prodotto matriciale
A = np.array([[1,12,7], [2,18,10], [3,1,4]])
B = np.array([[1,5,4], [6,11,2], [3,2,8]])
C = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Distributiva
D = np.matmul(A, B+C)
E = np.matmul(A, B) + np.matmul(A, C)
print("Matrice A(B+C):\n", D, "\n")
print("Matrice AB + AC:\n", E)

Matrice A(B+C):
 [[192 269 222]
 [284 402 328]
 [ 56  77  97]] 

Matrice AB + AC:
 [[192 269 222]
 [284 402 328]
 [ 56  77  97]]


In [ ]:
# Associativa
F = np.matmul(A, np.matmul(B, C))
G = np.matmul(np.matmul(A, B), C)
print("Matrice A(BC):\n", F, "\n")
print("Matrice (AB)C:\n", G)

Matrice A(BC):
 [[1286 1615 1944]
 [1920 2412 2904]
 [ 479  580  681]] 

Matrice (AB)C:
 [[1286 1615 1944]
 [1920 2412 2904]
 [ 479  580  681]]


In [ ]:
# Non vale la proprietà commutativa
H = np.matmul(A,B)
J = np.matmul(B,A)
print("Matrice AB:\n", H, "\n")
print("Matrice BA:\n", J)

Matrice AB:
 [[ 94 151  84]
 [140 228 124]
 [ 21  34  46]] 

Matrice BA:
 [[ 23 106  73]
 [ 34 272 160]
 [ 31  80  73]]


In [ ]:
# Il prodotto tra vettori è commutativo
x = np.array([1, 2, 3])
x = x.reshape(1,3)  # vettore riga attraverso reshape
print("Vettore x^T:\n", x)

y = np.array([4, 5, 6])
y = y.reshape(3,1)  # vettore colonna attraverso reshape
print("Vettore y:\n", y)

c = np.dot(x, y)
print("c = x^T y:\n",c)

x = x.reshape(3,1)  # vettore colonna attraverso reshape
print("Vettore x:\n", x)

y = y.reshape(1,3)  # vettore riga attraverso reshape
print("Vettore y^T:\n", y)

c = np.dot(y, x)
print("c = y^T x:\n",c)

Vettore x^T:
 [[1 2 3]]
Vettore y:
 [[4]
 [5]
 [6]]
c = x^T y:
 [[32]]
Vettore x:
 [[1]
 [2]
 [3]]
Vettore y^T:
 [[4 5 6]]
c = y^T x:
 [[32]]


In [ ]:
# Determinante di una matrice quadrata
det = np.linalg.det(A)
print(det)

-37.99999999999994


In [ ]:
# Inversa di una matrice quadrata non singolare
Ainv = np.linalg.inv(A)
print("Matrice A^{-1}:\n", Ainv, "\n\n")
print("Matrice A A^{-1}:\n", np.matmul(A,Ainv), "\n\n")

Matrice A^{-1}:
 [[-1.63157895  1.07894737  0.15789474]
 [-0.57894737  0.44736842 -0.10526316]
 [ 1.36842105 -0.92105263  0.15789474]] 


Matrice A A^{-1}:
 [[ 1.00000000e+00 -2.22044605e-16  2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] 




## Matrix cookbook

In [ ]:
# (A + B)^T = A^T + B^T
A = np.array([[1,12,7], [2,18,10], [3,1,4]])
B = np.array([[1,5,4], [6,11,2], [3,2,8]])

C = np.transpose(A + B)
D = np.transpose(A) + np.transpose(B)

print(C)
print(D)

[[ 2  8  6]
 [17 29  3]
 [11 12 12]]
[[ 2  8  6]
 [17 29  3]
 [11 12 12]]


In [ ]:
# (AB)^T = B^T A^T
C = np.transpose(np.matmul(A,B))
D = np.matmul(np.transpose(B), np.transpose(A))

print(C)
print(D)

[[ 94 140  21]
 [151 228  34]
 [ 84 124  46]]
[[ 94 140  21]
 [151 228  34]
 [ 84 124  46]]


In [ ]:
# (AB)^T = B^T A^T
C = np.linalg.inv(np.matmul(A,B))
D = np.matmul(np.linalg.inv(B), np.linalg.inv(A))

print(C)
print(D)

[[ 0.78596491 -0.51253133 -0.05363409]
 [-0.48070175  0.32080201  0.01303258]
 [-0.00350877 -0.00313283  0.03659148]]
[[ 0.78596491 -0.51253133 -0.05363409]
 [-0.48070175  0.32080201  0.01303258]
 [-0.00350877 -0.00313283  0.03659148]]


In [ ]:
# (A^T)^-1 = (A^-1)^T
C = np.linalg.inv(np.transpose(A))
D = np.transpose(np.linalg.inv(A))

print(C)
print(D)

[[-1.63157895 -0.57894737  1.36842105]
 [ 1.07894737  0.44736842 -0.92105263]
 [ 0.15789474 -0.10526316  0.15789474]]
[[-1.63157895 -0.57894737  1.36842105]
 [ 1.07894737  0.44736842 -0.92105263]
 [ 0.15789474 -0.10526316  0.15789474]]


In [ ]:
# det(c A) = cn det(A)
c = 2

det1 = np.linalg.det(c * A)
det2 = (c ** A.shape[0]) * np.linalg.det(A)

print(det1)
print(det2)

-303.9999999999995
-303.99999999999955


In [ ]:
# det(A^T) = det(A)
det1 = np.linalg.det(np.transpose(A))
det2 = np.linalg.det(A)

print(det1)
print(det2)

-37.99999999999993
-37.99999999999994


In [ ]:
# det(AB) = det(A)det(B)
det1 = np.linalg.det(np.matmul(A,B))
det2 = np.linalg.det(A) * np.linalg.det(B)

print(det1)
print(det2)

7979.999999999905
7979.999999999994


In [ ]:
# det(A^{-1}) = 1/det(A)
det1 = np.linalg.det(np.linalg.inv(A))
det2 = 1/np.linalg.det(A)

print(det1)
print(det2)

-0.02631578947368427
-0.02631578947368425


In [ ]:
# det(I + u v^T) = 1 + u^T v
u = np.array([1, 2, 3])
u = u.reshape(3,1)  # vettore colonna attraverso reshape
uT = u.reshape(1,3)  # vettore riga attraverso reshape

v = np.array([4, 5, 6])
vT = v.reshape(1,3)  # vettore riga attraverso reshape
v = v.reshape(3,1)  # vettore colonna attraverso reshape

det1 = np.linalg.det(np.identity(3) + np.dot(u, vT))
det2 = 1 + np.dot(uT, v)

print(det1)
print(det2)

32.99999999999997
[[33]]


## Sistemi di equazioni lineari

In [ ]:
# Rango di una matrice
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rango = np.linalg.matrix_rank(A)
print("Matrice A:\n", A, "\n")
print("Rank(A):", rango)

Matrice A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Rank(A): 2


In [ ]:
# Sistema Ax = b
A = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])
b = np.array([10,20,30,40])
x = np.linalg.solve(A, b)
print("x = ", x)

x =  [10. 20. 30. 40.]


In [ ]:
# verifichiamo che la soluzione sia corretta
print(np.allclose(np.matmul(A, x), b))

True


In [ ]:
# Sistema omogeneo
b = np.array([0,0,0,0])

x = np.linalg.solve(A, b)
print("x = ", x)

x =  [0. 0. 0. 0.]
